server:
  name: consul-server

  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:8600/udp"

  hostname: consul-server
  dns: 172.17.42.1
  dns_search: node.dc0

  build: server

agent:
  name: consul-agent
  links:
    - server

  hostname: consul-agent
  dns: 172.17.42.1
  dns_search: node.dc0

  build: agent
